server:
  port: 8080

spring:
  datasource:
    url: xxx
    username: xxx
    password: xxx
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none   # ilk geliştirme aşamasında "update", prod'da migration tool önerilir
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration

sharepoint:
  ag:
    host: "host"
    port: 443
    base-url: "companybaseurl"
    file: "fileurl"
  ak:
    base-url: ""
  ms:
    base-url: ""

logging:
  level:
    ROOT: DEBUG

app:
  jwt:
    secret: xxx
    access-ms: xxx
    refresh-ms: xxx