version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-server
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "MyCompany"
      LDAP_DOMAIN: "mycompany.com"
      LDAP_ADMIN_PASSWORD: admin
      LDAP_LOG_LEVEL: "256"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
      #- ./ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif:ro

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-server
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - "8090:80"
      ##- "6444:444"
    depends_on:
      - openldap

volumes:
  ldap-data:
  ldap-config:
